In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [6]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [15]:
def derivativesig(z):
    return sig(z)*(1 - sig(z))

In [8]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.60453609],
        [ 0.40806355]]), array([-0.98663898]))

In [9]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[ 0.27157645],
       [ 0.35926045],
       [ 0.16921864],
       [ 0.2344932 ]])

In [26]:
# one hidden layer weights
wh = 2* np.random.random((2, 2)) - 1
bh = 2* np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1,1)) - 1
lr = 0.1

In [27]:
# forward propagation with one hidden layer
for itr in range(10000):
    output0 = X
    inputhidden = np.dot(output0, wh) + bh
    outputHidden = sig(inputhidden)
    inputforoutputlayer = np.dot(outputHidden, wo) + bo
    output = sig(inputforoutputlayer)

    first_term_output_layer = output - Y
    second_term_output_layer = derivativesig(inputforoutputlayer)
    first_two_output_layer = first_term_output_layer*second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer = derivativesig(inputhidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer

    changes_output = np.dot(outputHidden.T,first_two_output_layer)
    changes_bias = np.sum(first_two_output_layer, axis = 0, keepdims = True)

    changes_hidden = np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis = 0, keepdims = True)

    wo = wo - lr*changes_output
    bo = bo-lr*changes_bias

    wh = wh - lr*changes_hidden
    bh = bh - lr*changes_hidden_bias
    
output0 = X
inputhidden = np.dot(output0, wh) + bh
outputHidden = sig(inputhidden)
inputforoutputlayer = np.dot(outputHidden, wo) + bo
output1 = sig(inputforoutputlayer)
output1,wh,bh,wo,bo

(array([[0.00130137],
        [0.02481408],
        [0.03911317],
        [0.95694154]]), array([[-3.02814258,  2.57579174],
        [-0.39277473,  4.13738614]]), array([[ 1.55268639, -4.7440359 ]]), array([[-4.2301773 ],
        [ 7.84773383]]), array([[-3.21957977]]))